#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Configure Nginx with custom header
echo "add_header X-Served-By \$hostname;" | sudo tee -a /etc/nginx/sites-available/default
sudo service nginx restart

