#!/usr/bin/env bash

# Install HAproxy
sudo apt-get update
sudo apt-get install -y haproxy

# Configure HAproxy
cat <<EOF | sudo tee -a /etc/haproxy/haproxy.cfg
frontend web-frontend
    bind *:80
    mode http
    default_backend web-backend

backend web-backend
    mode http
    balance roundrobin
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Enable HAproxy init script
sudo sed -i 's/ENABLED=0/ENABLED=1/' /etc/default/haproxy

# Restart HAproxy service
sudo service haproxy restart

