#!/bin/bash

MANAGE_SCRIPT="/full/path/to/manage_my_process"

case "$1" in
    start)
        $MANAGE_SCRIPT &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started"
        ;;
    stop)
        kill $(cat /var/run/my_process.pid)
        rm /var/run/my_process.pid
        echo "manage_my_process stopped"
        ;;
    restart)
        $0 stop
        $0 start
        echo "manage_my_process restarted"
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0

