#!/usr/bin/env bash
# Display "To infinity and beyond" indefinitely
# Display "I am invincible!!!" when receiving a SIGTERM signal
trap 'echo "I am invincible!!!"; exit' SIGTERM
while true
do
    echo "To infinity and beyond"
    sleep 2
done

