#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.1
#   - facebook.com resolves to 157.240.5.35

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.1 localhost\n157.240.5.35 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
